name: pixel_place
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.2

  # State managment
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3


  # Environment
  flutter_dotenv: ^5.1.0


  # Object Equality
  equatable: ^2.0.5



  # firebase
  firebase_analytics: 
  firebase_auth: 
  firebase_core: 
  firebase_core_web: 
  firebase_database: 
  firebase_storage: 
  json_annotation: ^4.8.1


  # di
  injectable: ^1.5.3
  get_it: ^7.6.7


  # Utilities
  flutter_colorpicker: ^1.0.3
  async: ^2.8.2
  jiffy: ^5.0.0
  
  


  
  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  injectable_generator: ^1.5.4
  json_serializable: ^6.1.4

flutter:
  uses-material-design: true
